### ISSUE TITLE
Decide front end stack for the project

### ISSUE THREAD

**Issue by iamareebjamal** [AMU-OSS/amu-oss-web#1]
Project needs to be deployable on gh-pages and hence needs a lightweight bundlable front-end JS framework with CLI building capabilities.

My recommendation is to go with Vue as it very less opinionated and easy to learn for beginners and the skills gained can be extended over React or Angular which are very specific and require steep learning curve

Other options are:
- Ember JS
- Meteor JS

**Comment by cRAN-cg** [comment]
Ok. Sounds like a plan. When are we planning to start btw ?

**Comment by RJ722** [comment]
I think we should start with a very basic skeleton, and then open issues (for extending development).

Some points to ponder:
* This needs us to think of content first.
* What features are needed? Does it needs to be dynamic (even initially)?

**Comment by iamareebjamal** [comment]
Guess we are settled on it now 👅
